import "../globals.css";
import { Button } from "@/components/ui/button";
import { MainNav } from "./components/main-nav";
import { UserNav } from "./components/user-nav";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col">
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              {/* <TeamSwitcher /> */}
              <MainNav className="mx-6" />
              <div className="ml-auto flex items-center space-x-4">
                {/* <Search /> */}
                <UserNav />
              </div>
            </div>
          </div>
          <div className="flex-1 space-y-4 p-8 pt-6">
            <div className="flex items-center justify-between space-y-2">
              <h2 className="text-3xl font-bold tracking-tight">Dashboard</h2>
              <div className="flex items-center space-x-2">
                {/* <CalendarDateRangePicker /> */}
                <Button>Download</Button>
              </div>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
